package:
  name: gitaly
  version: 17.0.1
  epoch: 0
  description: 
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - make
      - bash
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitaly.git
      tag: v${{package.version}}
      expected-commit: c1923eecc61a17b69312686f2aa57dcf124e203c

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

  - runs: |
      make install DESTDIR="${{targets.destdir}}" PREFIX=/usr

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 10037

test:
  pipeline:
    - runs: |
        gitaly -v | grep "${{package.version}}"
        gitaly-blackbox -version | grep "${{package.version}}"
        gitaly-backup -v | grep "${{package.version}}"