package:
  name: pixi
  version: 0.24.0
  epoch: 0
  description: "Package management made easy"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl
      - openssl-dev
      - perl
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prefix-dev/pixi
      expected-commit: 17d0bf4feb755eaba0a51b345058861f8c8c2d7f
      tag: v${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/pixi ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: prefix-dev/pixi
    strip-prefix: v

test:
  pipeline:
    - runs: pixi --version
