package:
  name: skopeo
  version: 1.16.0
  epoch: 0
  description: Work with remote images registries - retrieving information, images, signing content
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 88aad2e56b6bfcb5433450be60ff0a1cc89fcc31
      repository: https://github.com/containers/skopeo
      tag: v${{package.version}}

  - runs: |
      CGO_ENABLED=0 go build -mod=vendor \
        -tags "exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/skopeo" ./cmd/skopeo

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/skopeo
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - name: Verify Skopeo installation
      runs: |
        skopeo --version || exit 1
    - name: Validate image existence
      runs: |
        skopeo inspect docker://docker.io/chainguard/static:latest && echo "Image exists" || exit 1
    - name: List tags for a public image
      runs: |
        skopeo list-tags docker://docker.io/chainguard/static | jq -r '.Tags[]' | grep -E 'latest|v[0-9]+.[0-9]+.[0-9]+' || exit 1
    - name: Pull and save an image locally
      runs: |
        tmpdir=$(mktemp -d)
        skopeo copy --insecure-policy docker://docker.io/chainguard/static:latest dir:$tmpdir || exit 1
        [ -f $tmpdir/manifest.json ] || exit 1
